/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WriteupsIndexRouteImport } from './routes/writeups.index'
import { Route as WriteupsSlugRouteImport } from './routes/writeups.$slug'
import { Route as R9x7ktq3f8b2aGateRouteImport } from './routes/9x7ktq3f8b2a.gate'
import { Route as Authenticated9x7ktq3f8b2aPanelRouteImport } from './routes/_authenticated/9x7ktq3f8b2a.panel'
import { Route as Authenticated9x7ktq3f8b2aPanelIndexRouteImport } from './routes/_authenticated/9x7ktq3f8b2a.panel.index'
import { Route as Authenticated9x7ktq3f8b2aPanelNewRouteImport } from './routes/_authenticated/9x7ktq3f8b2a.panel.new'
import { Route as Authenticated9x7ktq3f8b2aPanelIdEditRouteImport } from './routes/_authenticated/9x7ktq3f8b2a.panel.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteupsIndexRoute = WriteupsIndexRouteImport.update({
  id: '/writeups/',
  path: '/writeups/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteupsSlugRoute = WriteupsSlugRouteImport.update({
  id: '/writeups/$slug',
  path: '/writeups/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const R9x7ktq3f8b2aGateRoute = R9x7ktq3f8b2aGateRouteImport.update({
  id: '/9x7ktq3f8b2a/gate',
  path: '/9x7ktq3f8b2a/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const Authenticated9x7ktq3f8b2aPanelRoute =
  Authenticated9x7ktq3f8b2aPanelRouteImport.update({
    id: '/9x7ktq3f8b2a/panel',
    path: '/9x7ktq3f8b2a/panel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Authenticated9x7ktq3f8b2aPanelIndexRoute =
  Authenticated9x7ktq3f8b2aPanelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Authenticated9x7ktq3f8b2aPanelRoute,
  } as any)
const Authenticated9x7ktq3f8b2aPanelNewRoute =
  Authenticated9x7ktq3f8b2aPanelNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => Authenticated9x7ktq3f8b2aPanelRoute,
  } as any)
const Authenticated9x7ktq3f8b2aPanelIdEditRoute =
  Authenticated9x7ktq3f8b2aPanelIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => Authenticated9x7ktq3f8b2aPanelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/9x7ktq3f8b2a/gate': typeof R9x7ktq3f8b2aGateRoute
  '/writeups/$slug': typeof WriteupsSlugRoute
  '/writeups/': typeof WriteupsIndexRoute
  '/9x7ktq3f8b2a/panel': typeof Authenticated9x7ktq3f8b2aPanelRouteWithChildren
  '/9x7ktq3f8b2a/panel/new': typeof Authenticated9x7ktq3f8b2aPanelNewRoute
  '/9x7ktq3f8b2a/panel/': typeof Authenticated9x7ktq3f8b2aPanelIndexRoute
  '/9x7ktq3f8b2a/panel/$id/edit': typeof Authenticated9x7ktq3f8b2aPanelIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/9x7ktq3f8b2a/gate': typeof R9x7ktq3f8b2aGateRoute
  '/writeups/$slug': typeof WriteupsSlugRoute
  '/writeups': typeof WriteupsIndexRoute
  '/9x7ktq3f8b2a/panel/new': typeof Authenticated9x7ktq3f8b2aPanelNewRoute
  '/9x7ktq3f8b2a/panel': typeof Authenticated9x7ktq3f8b2aPanelIndexRoute
  '/9x7ktq3f8b2a/panel/$id/edit': typeof Authenticated9x7ktq3f8b2aPanelIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/9x7ktq3f8b2a/gate': typeof R9x7ktq3f8b2aGateRoute
  '/writeups/$slug': typeof WriteupsSlugRoute
  '/writeups/': typeof WriteupsIndexRoute
  '/_authenticated/9x7ktq3f8b2a/panel': typeof Authenticated9x7ktq3f8b2aPanelRouteWithChildren
  '/_authenticated/9x7ktq3f8b2a/panel/new': typeof Authenticated9x7ktq3f8b2aPanelNewRoute
  '/_authenticated/9x7ktq3f8b2a/panel/': typeof Authenticated9x7ktq3f8b2aPanelIndexRoute
  '/_authenticated/9x7ktq3f8b2a/panel/$id/edit': typeof Authenticated9x7ktq3f8b2aPanelIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/9x7ktq3f8b2a/gate'
    | '/writeups/$slug'
    | '/writeups/'
    | '/9x7ktq3f8b2a/panel'
    | '/9x7ktq3f8b2a/panel/new'
    | '/9x7ktq3f8b2a/panel/'
    | '/9x7ktq3f8b2a/panel/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/9x7ktq3f8b2a/gate'
    | '/writeups/$slug'
    | '/writeups'
    | '/9x7ktq3f8b2a/panel/new'
    | '/9x7ktq3f8b2a/panel'
    | '/9x7ktq3f8b2a/panel/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/sitemap.xml'
    | '/9x7ktq3f8b2a/gate'
    | '/writeups/$slug'
    | '/writeups/'
    | '/_authenticated/9x7ktq3f8b2a/panel'
    | '/_authenticated/9x7ktq3f8b2a/panel/new'
    | '/_authenticated/9x7ktq3f8b2a/panel/'
    | '/_authenticated/9x7ktq3f8b2a/panel/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  R9x7ktq3f8b2aGateRoute: typeof R9x7ktq3f8b2aGateRoute
  WriteupsSlugRoute: typeof WriteupsSlugRoute
  WriteupsIndexRoute: typeof WriteupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writeups/': {
      id: '/writeups/'
      path: '/writeups'
      fullPath: '/writeups/'
      preLoaderRoute: typeof WriteupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writeups/$slug': {
      id: '/writeups/$slug'
      path: '/writeups/$slug'
      fullPath: '/writeups/$slug'
      preLoaderRoute: typeof WriteupsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/9x7ktq3f8b2a/gate': {
      id: '/9x7ktq3f8b2a/gate'
      path: '/9x7ktq3f8b2a/gate'
      fullPath: '/9x7ktq3f8b2a/gate'
      preLoaderRoute: typeof R9x7ktq3f8b2aGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/9x7ktq3f8b2a/panel': {
      id: '/_authenticated/9x7ktq3f8b2a/panel'
      path: '/9x7ktq3f8b2a/panel'
      fullPath: '/9x7ktq3f8b2a/panel'
      preLoaderRoute: typeof Authenticated9x7ktq3f8b2aPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/9x7ktq3f8b2a/panel/': {
      id: '/_authenticated/9x7ktq3f8b2a/panel/'
      path: '/'
      fullPath: '/9x7ktq3f8b2a/panel/'
      preLoaderRoute: typeof Authenticated9x7ktq3f8b2aPanelIndexRouteImport
      parentRoute: typeof Authenticated9x7ktq3f8b2aPanelRoute
    }
    '/_authenticated/9x7ktq3f8b2a/panel/new': {
      id: '/_authenticated/9x7ktq3f8b2a/panel/new'
      path: '/new'
      fullPath: '/9x7ktq3f8b2a/panel/new'
      preLoaderRoute: typeof Authenticated9x7ktq3f8b2aPanelNewRouteImport
      parentRoute: typeof Authenticated9x7ktq3f8b2aPanelRoute
    }
    '/_authenticated/9x7ktq3f8b2a/panel/$id/edit': {
      id: '/_authenticated/9x7ktq3f8b2a/panel/$id/edit'
      path: '/$id/edit'
      fullPath: '/9x7ktq3f8b2a/panel/$id/edit'
      preLoaderRoute: typeof Authenticated9x7ktq3f8b2aPanelIdEditRouteImport
      parentRoute: typeof Authenticated9x7ktq3f8b2aPanelRoute
    }
  }
}

interface Authenticated9x7ktq3f8b2aPanelRouteChildren {
  Authenticated9x7ktq3f8b2aPanelNewRoute: typeof Authenticated9x7ktq3f8b2aPanelNewRoute
  Authenticated9x7ktq3f8b2aPanelIndexRoute: typeof Authenticated9x7ktq3f8b2aPanelIndexRoute
  Authenticated9x7ktq3f8b2aPanelIdEditRoute: typeof Authenticated9x7ktq3f8b2aPanelIdEditRoute
}

const Authenticated9x7ktq3f8b2aPanelRouteChildren: Authenticated9x7ktq3f8b2aPanelRouteChildren =
  {
    Authenticated9x7ktq3f8b2aPanelNewRoute:
      Authenticated9x7ktq3f8b2aPanelNewRoute,
    Authenticated9x7ktq3f8b2aPanelIndexRoute:
      Authenticated9x7ktq3f8b2aPanelIndexRoute,
    Authenticated9x7ktq3f8b2aPanelIdEditRoute:
      Authenticated9x7ktq3f8b2aPanelIdEditRoute,
  }

const Authenticated9x7ktq3f8b2aPanelRouteWithChildren =
  Authenticated9x7ktq3f8b2aPanelRoute._addFileChildren(
    Authenticated9x7ktq3f8b2aPanelRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  Authenticated9x7ktq3f8b2aPanelRoute: typeof Authenticated9x7ktq3f8b2aPanelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  Authenticated9x7ktq3f8b2aPanelRoute:
    Authenticated9x7ktq3f8b2aPanelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  R9x7ktq3f8b2aGateRoute: R9x7ktq3f8b2aGateRoute,
  WriteupsSlugRoute: WriteupsSlugRoute,
  WriteupsIndexRoute: WriteupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
